name: My Workflow

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Vous pouvez spécifier la version de PHP que vous utilisez

    - name: Install Composer dependencies
      run: composer install 

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit
